---
#  Copyright (c) 2018 Red Hat, Inc.
#
#  This file is part of ARA Records Ansible.
#
#  ARA is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  ARA is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with ARA.  If not, see <http://www.gnu.org/licenses/>.

# This runs the ARA role with parameters to set up nginx as a reverse proxy to
# the embedded server. The web application will be available on '/ara'.
- name: Install ARA with nginx as reverse proxy to the embedded server
  hosts: localhost
  vars:
    ara_override:
      config:
        application_root: /ara
      deployment:
        server: nginx
        type: embedded_proxy
  roles:
    - ara
