---
# tasks file for roles/mdopen
- name: "Install Openidc installation package"
  yum:
    name:  "{{ item }}"
    state: present
    validate_certs: no
  become: yes
  become_user: root
  with_items:
    - mod_auth_openidc
    - mod_ssl 

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
