
- name: Template Openidc configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: 'openidc.conf.j2', dest: '/etc/httpd/conf.d/openidc.conf' }
  notify:
    - restart httpd

